        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 23 09:41:08 2018
        MODULE ANGLE_FACE__genmod
          INTERFACE 
            SUBROUTINE ANGLE_FACE
            END SUBROUTINE ANGLE_FACE
          END INTERFACE 
        END MODULE ANGLE_FACE__genmod
