        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 17 09:42:41 2018
        MODULE CAL_WALLNUMBER__genmod
          INTERFACE 
            SUBROUTINE CAL_WALLNUMBER
            END SUBROUTINE CAL_WALLNUMBER
          END INTERFACE 
        END MODULE CAL_WALLNUMBER__genmod
