        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 07 11:19:53 2018
        MODULE CAL_WALLNUMBER__genmod
          INTERFACE 
            SUBROUTINE CAL_WALLNUMBER
            END SUBROUTINE CAL_WALLNUMBER
          END INTERFACE 
        END MODULE CAL_WALLNUMBER__genmod
