        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 17 09:42:40 2018
        MODULE COUNT_MAX__genmod
          INTERFACE 
            SUBROUTINE COUNT_MAX
            END SUBROUTINE COUNT_MAX
          END INTERFACE 
        END MODULE COUNT_MAX__genmod
