        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 27 11:13:29 2018
        MODULE COUNT__genmod
          INTERFACE 
            SUBROUTINE COUNT
            END SUBROUTINE COUNT
          END INTERFACE 
        END MODULE COUNT__genmod
