        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 07 11:19:53 2018
        MODULE COUNT_MAX__genmod
          INTERFACE 
            SUBROUTINE COUNT_MAX
            END SUBROUTINE COUNT_MAX
          END INTERFACE 
        END MODULE COUNT_MAX__genmod
