        !COMPILER-GENERATED INTERFACE MODULE: Tue Nov 27 15:28:00 2018
        MODULE DISTANCE__genmod
          INTERFACE 
            SUBROUTINE DISTANCE
            END SUBROUTINE DISTANCE
          END INTERFACE 
        END MODULE DISTANCE__genmod
