        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 07 11:19:53 2018
        MODULE GRID_QUALITY__genmod
          INTERFACE 
            SUBROUTINE GRID_QUALITY
            END SUBROUTINE GRID_QUALITY
          END INTERFACE 
        END MODULE GRID_QUALITY__genmod
