        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 17 10:23:29 2018
        MODULE GRID_QUALITY__genmod
          INTERFACE 
            SUBROUTINE GRID_QUALITY
            END SUBROUTINE GRID_QUALITY
          END INTERFACE 
        END MODULE GRID_QUALITY__genmod
