        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 17 10:23:29 2018
        MODULE RADIAL_BASIS_FUNCTION__genmod
          INTERFACE 
            SUBROUTINE RADIAL_BASIS_FUNCTION(FUNC_NUM)
              INTEGER(KIND=4) :: FUNC_NUM
            END SUBROUTINE RADIAL_BASIS_FUNCTION
          END INTERFACE 
        END MODULE RADIAL_BASIS_FUNCTION__genmod
