        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 07 21:28:15 2018
        MODULE READ_BOUNDARY_CONDITION__genmod
          INTERFACE 
            SUBROUTINE READ_BOUNDARY_CONDITION
            END SUBROUTINE READ_BOUNDARY_CONDITION
          END INTERFACE 
        END MODULE READ_BOUNDARY_CONDITION__genmod
