        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 17 09:42:41 2018
        MODULE READ_BOUNDARY_CONDITION__genmod
          INTERFACE 
            SUBROUTINE READ_BOUNDARY_CONDITION
            END SUBROUTINE READ_BOUNDARY_CONDITION
          END INTERFACE 
        END MODULE READ_BOUNDARY_CONDITION__genmod
