        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 07 11:19:53 2018
        MODULE ROTATE__genmod
          INTERFACE 
            SUBROUTINE ROTATE(X_ROTATE_CENTER,Y_ROTATE_CENTER,THETA)
              REAL(KIND=4) :: X_ROTATE_CENTER
              REAL(KIND=4) :: Y_ROTATE_CENTER
              REAL(KIND=4) :: THETA
            END SUBROUTINE ROTATE
          END INTERFACE 
        END MODULE ROTATE__genmod
