        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 07 11:19:53 2018
        MODULE TFI_PARAMETER__genmod
          INTERFACE 
            SUBROUTINE TFI_PARAMETER
            END SUBROUTINE TFI_PARAMETER
          END INTERFACE 
        END MODULE TFI_PARAMETER__genmod
