        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 17 09:42:41 2018
        MODULE TFI_PARAMETER__genmod
          INTERFACE 
            SUBROUTINE TFI_PARAMETER
            END SUBROUTINE TFI_PARAMETER
          END INTERFACE 
        END MODULE TFI_PARAMETER__genmod
